language: php
php:
    - 7.1
    - 7.0

matrix:
    fast_finish: true

install:
    - composer install

script:
    - mkdir -p build/logs
    - composer test

after_script:
    - composer require satooshi/php-coveralls
    - travis_retry php vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml
